#pragma once

#define WIFI_SSID_VALUE "YOUR_WIFI_SSID"
#define WIFI_PASS_VALUE "YOUR_WIFI_PASSWORD"
#define WIFI_TCP_PORT_VALUE 5000
#define WIFI_DEVICE_NAME_VALUE "R4_WIFI35"
#define PAIRED_HOST_LABEL_VALUE "Unassigned"
#define PAIRED_HOSTNAME_VALUE ""
#define PAIRED_BOARD_ASSIGNMENT_VALUE ""
