#pragma once

#define WIFI_SSID_VALUE "YOUR_WIFI_SSID"
#define WIFI_PASS_VALUE "YOUR_WIFI_PASSWORD"
#define WIFI_TCP_PORT_VALUE 5000
#define WIFI_DEVICE_NAME_VALUE "R4_WIFI35"
#define WIFI_TARGET_HOST_VALUE ""
#define WIFI_TARGET_HOSTNAME_VALUE ""
